package gherkinexecutor.Feature_Game_of_Life;
import org.junit.jupiter.api.*;
import java.util.List;
@SuppressWarnings({"NewClassNamingConvention"})
class Feature_Game_of_Life{


    @Test
    void test_Scenario_Output_and_Conversion_work(){
         Feature_Game_of_Life_glue feature_Game_of_Life_glue_object = new Feature_Game_of_Life_glue();

        List<List<String>> stringListList1 = List.of(
           List.of(
            ""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Given_generation_is(stringListList1);

        feature_Game_of_Life_glue_object.When_output();

        List<List<String>> stringListList3 = List.of(
           List.of(
            ""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList3);
        }
    @Test
    void test_Scenario_Block(){
         Feature_Game_of_Life_glue feature_Game_of_Life_glue_object = new Feature_Game_of_Life_glue();

        List<List<String>> stringListList1 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Given_generation_is(stringListList1);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList3 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList3);
        }
    @Test
    void test_Scenario_Blinker(){
         Feature_Game_of_Life_glue feature_Game_of_Life_glue_object = new Feature_Game_of_Life_glue();

        List<List<String>> stringListList1 = List.of(
           List.of(
            ""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Given_generation_is(stringListList1);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList3 = List.of(
           List.of(
            ""
            ,""
            ,""
            )
           ,List.of(
            "X"
            ,"X"
            ,"X"
            )
           ,List.of(
            ""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList3);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList5 = List.of(
           List.of(
            ""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList5);
        }
    @Test
    void test_Scenario_Toad(){
         Feature_Game_of_Life_glue feature_Game_of_Life_glue_object = new Feature_Game_of_Life_glue();

        List<List<String>> stringListList1 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Given_generation_is(stringListList1);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList3 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            ,""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            ,""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList3);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList5 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList5);
        }
    @Test
    void test_Scenario_Glider(){
         Feature_Game_of_Life_glue feature_Game_of_Life_glue_object = new Feature_Game_of_Life_glue();

        List<List<String>> stringListList1 = List.of(
           List.of(
            ""
            ,"X"
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            "X"
            ,"X"
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Given_generation_is(stringListList1);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList3 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            "X"
            ,""
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList3);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList5 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            "X"
            ,""
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList5);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList7 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList7);

        feature_Game_of_Life_glue_object.When_tick();

        List<List<String>> stringListList9 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,"X"
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Then_generation_is_now(stringListList9);
        }
    @Test
    void test_Scenario_Examples_for_main_program(){
         Feature_Game_of_Life_glue feature_Game_of_Life_glue_object = new Feature_Game_of_Life_glue();

        List<List<String>> stringListList1 = List.of(
           List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,"X"
            ,"X"
            ,""
            )
           ,List.of(
            ""
            ,""
            ,"X"
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,"X"
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
           ,List.of(
            ""
            ,""
            ,""
            ,""
            ,""
            ,""
            )
            );
        feature_Game_of_Life_glue_object.Given_generation_is(stringListList1);
        }
    }

